title: the butler and the jihad
email: ethanrlee15@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  The place where I can share poorly written ideas i've been thinking about
baseurl: ""
url: "https://ethrlee.github.io"
instagram_username: ethan.rlee
# github_username: ethrlee
# twitter_username: your_twitter_handle


# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
